{
  "httpHeaders": {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  },
  "retryCount": 3,
  "retryOn": [403, 429, 500, 502, 503, 504],
  "ignorePatterns": [
    { "pattern": ".*(localhost|127.0.0.1).*" }
  ],
  "aliveStatusCodes": [200, 206, 301, 302, 429]
}
