name: Build docs, check CloudFormation, check for dead links
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read

jobs:
  check:
    name: build docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository 
      uses: actions/checkout@v6
    - name: Build documentation
      run: docker run --rm -v "$PWD":/docs -w /docs swift:6.2 swift run VaporDocs
    - name: Setup cloudformation linter 
      uses: ScottBrenner/cfn-lint-action@ed184e91f5085a2932501da8314e899e5e0ef5be # v2.7.1
    - name: Run cloudformation lint 
      run: cfn-lint -t stack.yml
    - name: Run dead links check
      uses: tcort/github-action-markdown-link-check@e7c7a18363c842693fadde5d41a3bd3573a7a225 # v1.1.2
      with:
        folder-path: '.'
        config-file: markdown-link-check-config.yml
        use-verbose-mode: yes
        use-quiet-mode: yes
