name: PR - Closed

on:
  pull_request:
    branches:
      - main
    types: [closed]

permissions:
  id-token: write
  deployments: write
  contents: read

jobs:
  delete-s3:
    name: Delete S3 preview
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.full_name == 'vapor/docs' && github.event.pull_request.user.login != 'dependabot[bot]' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          role-to-assume: ${{ vars.OIDC_ROLE_ARN }}
          aws-region: ${{ vars.OIDC_ROLE_REGION }}
      - name: Delete preview bucket
        uses: brokenhandsio/s3-website-pr-action@9461e5d13f1c56290b8a006546dd5e845ef2c671 # v3.0.1
        with:
          bucket-prefix: "vapor-docs-pulls"
          bucket-region: "us-east-1"
