name: Check PR and create issue for translation

on:
  push:
    branches:
      - main

jobs:
  create:
    name: Create issue
    runs-on: ubuntu-latest
    steps:
    - name: Find PR
      uses: 8BitJonny/gh-get-current-pr@2.1.0
      id: find-pr
      with:
        state: all
    - uses: actions/checkout@v2
    - name: Create issue
      if: steps.find-pr.outputs.number && !contains(steps.find-pr.outputs.pr_labels, 'translation-update') && !contains(steps.find-pr.outputs.pr_labels, 'no-translation-needed')
      uses: JasonEtco/create-an-issue@v2
      env:
        PR_NUMBER: ${{ steps.find-pr.outputs.number }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/workflows/translation-issue-template.md